spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: kris
    password: kris
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgresSQLDialect
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments
